# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DateDialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(458, 349)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.timeCheckBox = QtWidgets.QCheckBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeCheckBox.sizePolicy().hasHeightForWidth())
        self.timeCheckBox.setSizePolicy(sizePolicy)
        self.timeCheckBox.setObjectName("timeCheckBox")
        self.horizontalLayout_2.addWidget(self.timeCheckBox)
        self.amButton = QtWidgets.QRadioButton(self.widget_3)
        self.amButton.setEnabled(False)
        self.amButton.setChecked(True)
        self.amButton.setObjectName("amButton")
        self.horizontalLayout_2.addWidget(self.amButton)
        self.pmButton = QtWidgets.QRadioButton(self.widget_3)
        self.pmButton.setEnabled(False)
        self.pmButton.setObjectName("pmButton")
        self.horizontalLayout_2.addWidget(self.pmButton)
        self.timeEdit = QtWidgets.QTimeEdit(self.widget_3)
        self.timeEdit.setEnabled(False)
        self.timeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.timeEdit.setMaximumTime(QtCore.QTime(23, 59, 59))
        self.timeEdit.setCalendarPopup(False)
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout_2.addWidget(self.timeEdit)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.noneButton = QtWidgets.QRadioButton(self.widget_2)
        self.noneButton.setObjectName("noneButton")
        self.verticalLayout_4.addWidget(self.noneButton)
        self.singularButton = QtWidgets.QRadioButton(self.widget_2)
        self.singularButton.setChecked(True)
        self.singularButton.setObjectName("singularButton")
        self.verticalLayout_4.addWidget(self.singularButton)
        self.recurringButton = QtWidgets.QRadioButton(self.widget_2)
        self.recurringButton.setObjectName("recurringButton")
        self.verticalLayout_4.addWidget(self.recurringButton)
        self.horizontalLayout.addWidget(self.widget_2)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.widget)
        self.verticalLayout_2.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.singularButton.clicked.connect(Dialog.singularClicked)
        self.recurringButton.clicked.connect(Dialog.recurringClicked)
        self.timeCheckBox.toggled['bool'].connect(Dialog.timeCheckBoxToggle)
        self.amButton.clicked.connect(Dialog.amSelected)
        self.pmButton.clicked.connect(Dialog.pmSelected)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.timeCheckBox.setText(_translate("Dialog", "Time"))
        self.amButton.setText(_translate("Dialog", "AM"))
        self.pmButton.setText(_translate("Dialog", "PM"))
        self.timeEdit.setDisplayFormat(_translate("Dialog", "hh:mm ap"))
        self.noneButton.setText(_translate("Dialog", "None"))
        self.singularButton.setText(_translate("Dialog", "Singular"))
        self.recurringButton.setText(_translate("Dialog", "Recurring"))
